# Generated by Django 4.2.5 on 2023-09-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='paid',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment',
            field=models.CharField(default='Not specified', max_length=100),
        ),
    ]
